version: '3'
services:
  apprendre.co-mailcatcher:
    build: .
    container_name: mailCatcher
    restart: unless-stopped
    ports:
     - "1025:1025"
    environment:
     VIRTUAL_HOST: "mail.localhost"

networks:
    default:
       external:
               name: webproxy

